"use client";

import type { Metadata } from "next";
import { Ubuntu, Bungee_Shade, Gugi, Archivo_Black } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/wrappers/sessionWrapper";
import Header from "@/components/wrappers/header";
import Footer from "@/components/wrappers/footer";
import { usePathname } from "next/navigation";
import SigninHeader from "@/components/wrappers/signinHeader";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "300",
});
const bungee_Shade = Bungee_Shade({
  subsets: ["latin"],
  weight: "400",
});
const gugi = Gugi({
  subsets: ["latin"],
  weight: "400",
});
const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <SessionWrapper>
        <body
          className={` ${ubuntu.className}${bungee_Shade.className}${gugi.className}${archivoBlack.className}`}
        >
          {pathname === "/signin" || pathname === "/signup" ? (
            <SigninHeader />
          ) : (
            <Header />
          )}
          {children}
          <Footer />
        </body>
      </SessionWrapper>
    </html>
  );
}
