import type { Metadata } from "next";
import { Ubuntu, Bungee_Shade, Gugi, Archivo_Black } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/components/wrappers/sessionWrapper";
import Header from "@/components/wrappers/header";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "300",
});
const bungee_Shade = Bungee_Shade({
  subsets: ["latin"],
  weight: "400",
});
const gugi = Gugi({
  subsets: ["latin"],
  weight: "400",
});
const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionWrapper>
        <body
          className={` ${ubuntu.className}${bungee_Shade.className}${gugi.className}${archivoBlack.className}`}
        >
          <Header />
          {children}
        </body>
      </SessionWrapper>
    </html>
  );
}
