import type { Metadata } from "next";
import { Inter, Ubuntu, Bungee_Shade } from "next/font/google";
import "./globals.css";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "300",
});
const bungee_Shade = Bungee_Shade({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${ubuntu.className}${bungee_Shade.className}`}>
        {children}
      </body>
    </html>
  );
}
